# Generated by Django 4.2.1 on 2023-05-23 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SuperID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COA',
            fields=[
                ('SubID', models.AutoField(primary_key=True, serialize=False)),
                ('composite_key', models.CharField(max_length=255, unique=True)),
                ('AccountName', models.CharField(blank=True, max_length=30, null=True)),
                ('To_Increase', models.CharField(max_length=10)),
                ('AccountCategory', models.CharField(max_length=15)),
                ('AccountDesciption', models.CharField(blank=True, max_length=100, null=True)),
                ('SuperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.supercoa')),
            ],
        ),
    ]
