# Generated by Django 4.2.1 on 2023-05-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCOA',
            fields=[
                ('SuperID', models.IntegerField(primary_key=True, serialize=False)),
                ('SuperID_Name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COA',
            fields=[
                ('SuperID', models.IntegerField()),
                ('SubID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(blank=True, max_length=30, null=True)),
                ('To_Increase', models.CharField(max_length=10)),
                ('AccountCategory', models.CharField(max_length=15)),
                ('AccountDescription', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('SuperID', 'SubID')},
            },
        ),
    ]
