# Generated by Django 4.2.1 on 2023-06-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubID', models.IntegerField()),
                ('concatenated_id', models.CharField(max_length=100, unique=True)),
                ('AccountName', models.CharField(blank=True, max_length=30, null=True)),
                ('To_Increase', models.CharField(max_length=10)),
                ('AccountCategory', models.CharField(max_length=15)),
                ('AccountDescription', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('JournalID', models.AutoField(primary_key=True, serialize=False)),
                ('DateRealized', models.DateTimeField(null=True)),
                ('DateInputted', models.DateTimeField(null=True)),
                ('JournalDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('Receipt', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SuperCOA',
            fields=[
                ('SuperID', models.IntegerField(primary_key=True, serialize=False)),
                ('SuperID_Name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebitedAccount',
            fields=[
                ('DebitID', models.AutoField(primary_key=True, serialize=False)),
                ('DebitAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.coa')),
            ],
        ),
        migrations.CreateModel(
            name='CreditedAccount',
            fields=[
                ('CreditID', models.AutoField(primary_key=True, serialize=False)),
                ('CreditAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.coa')),
            ],
        ),
        migrations.AddField(
            model_name='coa',
            name='SuperID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.supercoa'),
        ),
    ]
