# Generated by Django 4.2.1 on 2023-05-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0004_coa_concatenated_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='SubID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coa',
            name='concatenated_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
