# Generated by Django 4.2.1 on 2023-05-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0005_alter_coa_subid_alter_coa_concatenated_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('JournalID', models.AutoField(primary_key=True, serialize=False)),
                ('DebitedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreditedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JournalDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('CreditedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credited_entries', to='CFO.coa')),
                ('DebitedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debited_entries', to='CFO.coa')),
            ],
        ),
    ]
