# Generated by Django 4.2.1 on 2023-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0006_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='DateInputted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='DateRealized',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='Receipt',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
