# Generated by Django 4.2.1 on 2023-05-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0007_journalentry_dateinputted_journalentry_daterealized_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='CreditedAccount',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='CreditedAmount',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='DebitedAccount',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='DebitedAmount',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionCategory', models.CharField(max_length=15)),
                ('TransactionAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JournalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.journalentry')),
            ],
        ),
    ]
