# Generated by Django 4.2.1 on 2023-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0008_remove_journalentry_creditedaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='AccountDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='JournalDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
