# Generated by Django 4.0.2 on 2023-05-25 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0009_alter_coa_accountdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditedAccount',
            fields=[
                ('CreditID', models.AutoField(primary_key=True, serialize=False)),
                ('CreditAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JournalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='DebitedAccount',
            fields=[
                ('DebitID', models.AutoField(primary_key=True, serialize=False)),
                ('DebitAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JournalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.journalentry')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
