# Generated by Django 4.2.1 on 2023-05-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0012_remove_creditedaccount_journalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditedaccount',
            name='COA_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.coa'),
        ),
        migrations.AlterField(
            model_name='debitedaccount',
            name='COA_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFO.coa'),
        ),
    ]
