# Generated by Django 4.2.1 on 2023-05-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0013_alter_creditedaccount_coa_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditedaccount',
            name='COA_ID',
        ),
        migrations.RemoveField(
            model_name='debitedaccount',
            name='COA_ID',
        ),
    ]
