# Generated by Django 4.2.1 on 2023-05-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0014_remove_creditedaccount_coa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditedaccount',
            name='COA_ID',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='debitedaccount',
            name='COA_ID',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
