# Generated by Django 4.2.1 on 2023-05-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFO', '0015_creditedaccount_coa_id_debitedaccount_coa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditedaccount',
            name='COA_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CFO.coa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debitedaccount',
            name='COA_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CFO.coa'),
            preserve_default=False,
        ),
    ]
